import { parse } from "yaml";

export interface LoopConfig { prompt: string; select: { epic: number | null; status: string; labels: string[]; updated_before?: string; limit: number; scan_budget: number; order: "oldest" | "newest" }; apply: { allowed_status: string[]; assign_owner: boolean; dry_run: boolean }; report_issue: number | null }
export interface OctestraConfig { version: 1; github_app: { client_id: string }; runners: { orchestration: string; agent: string }; status: { field_name: string; field_id: string; options: Record<string, string> }; branch: { task: string; loop: string }; prompts: { lifecycle_in_progress: string; lifecycle_validation: string }; loops: Record<string, LoopConfig> }
export interface ConfigClient { getContent(path: string, ref?: string): Promise<string> }
const object = (value: unknown, name: string): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`config.yml ${name} must be a mapping`); return value as Record<string, unknown>; };
const string = (value: unknown, name: string): string => { if (typeof value !== "string" || !value.trim()) throw new Error(`config.yml ${name} must be a non-empty string`); return value.trim(); };
const positive = (value: unknown, name: string): number => { if (!Number.isSafeInteger(value) || (value as number) <= 0) throw new Error(`config.yml ${name} must be a positive integer`); return value as number; };
export function parseOctestraConfig(raw: string): OctestraConfig {
 const root=object(parse(raw), "root"); if(root.version!==1) throw new Error("config.yml version must be 1");
 const app=object(root.github_app,"github_app"), runners=object(root.runners,"runners"), status=object(root.status,"status"), options=object(status.options,"status.options"), branch=object(root.branch,"branch"), prompts=object(root.prompts,"prompts");
 const requiredOptions=["todo","ready","in_progress","validation","human_review","blocked","done"];
 for(const key of requiredOptions) string(options[key],`status.options.${key}`);
 const loops: Record<string, LoopConfig>={}; const rawLoops=root.loops ?? {}; for(const [id,value] of Object.entries(object(rawLoops,"loops"))){
  if(!/^[a-z0-9][a-z0-9-]*$/.test(id)) throw new Error(`config.yml loops.${id} must use a lowercase slug`); const loop=object(value,`loops.${id}`), select=object(loop.select,`loops.${id}.select`), apply=object(loop.apply,`loops.${id}.apply`); const labels=select.labels ?? []; if(!Array.isArray(labels)||labels.some(x=>typeof x!=="string"||!x.trim())) throw new Error(`config.yml loops.${id}.select.labels must be strings`); const epic=select.epic ?? null; if(epic!==null) positive(epic,`loops.${id}.select.epic`); if(epic===null&&labels.length===0) throw new Error(`config.yml loops.${id} must set select.epic or select.labels`); const order=select.order ?? "oldest"; if(order!=="oldest"&&order!=="newest") throw new Error(`config.yml loops.${id}.select.order must be oldest or newest`); const allowed=apply.allowed_status; if(!Array.isArray(allowed)||allowed.some(x=>typeof x!=="string"||!x.trim())) throw new Error(`config.yml loops.${id}.apply.allowed_status must be strings`); if(typeof apply.assign_owner!=="boolean"||typeof apply.dry_run!=="boolean") throw new Error(`config.yml loops.${id}.apply assign_owner and dry_run must be booleans`); loops[id]={prompt:string(loop.prompt,`loops.${id}.prompt`),select:{epic: epic as number | null,status:string(select.status,`loops.${id}.select.status`),labels,updated_before:select.updated_before===undefined?undefined:string(select.updated_before,`loops.${id}.select.updated_before`),limit:positive(select.limit,`loops.${id}.select.limit`),scan_budget:positive(select.scan_budget,`loops.${id}.select.scan_budget`),order},apply:{allowed_status:allowed as string[],assign_owner:apply.assign_owner as boolean,dry_run:apply.dry_run as boolean},report_issue:loop.report_issue===null||loop.report_issue===undefined?null:positive(loop.report_issue,`loops.${id}.report_issue`)};
 }
 return {version:1,github_app:{client_id:string(app.client_id,"github_app.client_id")},runners:{orchestration:string(runners.orchestration,"runners.orchestration"),agent:string(runners.agent,"runners.agent")},status:{field_name:string(status.field_name,"status.field_name"),field_id:string(status.field_id,"status.field_id"),options:Object.fromEntries(Object.entries(options).map(([k,v])=>[k,string(v,`status.options.${k}`)]))},branch:{task:string(branch.task,"branch.task"),loop:string(branch.loop,"branch.loop")},prompts:{lifecycle_in_progress:string(prompts.lifecycle_in_progress,"prompts.lifecycle_in_progress"),lifecycle_validation:string(prompts.lifecycle_validation,"prompts.lifecycle_validation")},loops};
}
export async function loadOctestraConfig(client: ConfigClient, ref?: string): Promise<OctestraConfig> { return parseOctestraConfig(await client.getContent(".github/octestra/config.yml", ref || undefined)); }
